// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRVercDDY4vkWzyAmFIMKnhlkKQI0NWCw',
    appId: '1:218493434420:web:e9d0ffa8f839d9de546861',
    messagingSenderId: '218493434420',
    projectId: 'bully-alert-application',
    authDomain: 'bully-alert-application.firebaseapp.com',
    storageBucket: 'bully-alert-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbCXz9rZi8P2g8tJBwvu39nj4-Nd9gB5E',
    appId: '1:218493434420:android:fb9212f69e0fffbc546861',
    messagingSenderId: '218493434420',
    projectId: 'bully-alert-application',
    storageBucket: 'bully-alert-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_g-rpGtPEy5zrXjDIDtnqFxvgvt0WO40',
    appId: '1:218493434420:ios:2334ea343025a190546861',
    messagingSenderId: '218493434420',
    projectId: 'bully-alert-application',
    storageBucket: 'bully-alert-application.firebasestorage.app',
    iosBundleId: 'com.example.bullyAlert',
  );
}
